# https://raw.githubusercontent.com/flightlessmango/MangoHud/master/data/MangoHud.conf

# Preset
preset=-1,0,1,2
# Layout
font_file=/home/nico/.local/share/fonts/tx-02/TX-02-Medium.ttf

font_size=22
font_size_secondary=18

text_outline_thickness = 1

# Colors
gpu_color=76B900
cpu_color=0068B5

# Labels
fps_text=FPS

# Misc


# Shortcuts
toggle_hud=Shift_L+F12
toggle_hud_position=Shift_L+F11
toggle_preset=Shift_L+F10
reset_fps_metrics=Shift_L+F9

reload_cfg=Shift_L+F4

toggle_fps_limit=
toggle_logging= 
upload_log=
