
# FPS 
[preset -1]
fps_only
hud_no_margin
background_alpha=0
position=top-right 
# Default
[preset 0]

gpu_temp
gpu_fan
gpu_power
cpu_temp

# Horizontal
[preset 1]
horizontal
hud_no_margin
horizontal_separator_color=FFFFFF
gpu_temp
cpu_temp

# Detailed
[preset 2]
cpu_stats
gpu_stats

gpu_temp
gpu_fan
gpu_power
cpu_temp


ram
vram
io_read
io_write

fps_metrics=avg,0.01
dynamic_frame_timing