# Enable fan control
Section "Device"
	Identifier     "Device0"
	Driver         "nvidia"
	Option         "Coolbits" "4"
EndSection

#Section "Monitor"
#	Identifier     "Monitor0"
#	VendorName     "ASUS"
#	ModelName      "PG279Q"
#	VertRefresh     48.0 - 144.0
#	Option         "DPMS"
#EndSection
