# For some devices (such as laptop displays), GNOME/Plasma may not recognize VRR capability under Wayland, despite the display supporting it (and advertising support via EDID).
# This may be caused by your greeter (such as GDM/SDDM) running on X11, while your desktop session is running on Wayland. To fix this, configure your greeter to use Wayland instead (see: SDDM#Wayland).
# https://wiki.archlinux.org/title/Variable_refresh_rate#Monitor_does_not_show_up_as_VRR_capable_in_Wayland,_despite_supporting_it
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
