# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#default-prompt-format
right_format = """
$time
"""

[time]
disabled = false
format = '[$time]($style) '
style="248"
time_format = '%T'
utc_time_offset = 'local'


# Disable git-status for now, it absolutely kills performance for the whole shell on myHDD.
[git_status]
disabled = true

[env_var.NODE_ENV]
variable = 'NODE_ENV'
format = '[NODE_ENV=$env_value]($style) '


# Custom
[bun]
format = '([$symbol($version )]($style))'
symbol = "Bun "
style = "bold 8"

[nodejs]
format = '([$symbol($version )]($style))'
version_format = 'v${major}'
symbol = " "

[python]
format = '([${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'
detect_folders = ['.venv', 'venv']
symbol = " "

# Preset: No empty icons
[aws]
symbol = "  "

[buf]
format = '(with [$symbol$version ]($style))'
symbol = " "

[c]
format = '([$symbol($version(-$name) )]($style))'
symbol = " "

[cmake]
format = '([$symbol($version )]($style))'

[cobol]
format = '([$symbol($version )]($style))'

[conda]
symbol = " "

[crystal]
format = '([$symbol($version )]($style))'
symbol = " "

[daml]
format = '([$symbol($version )]($style))'

[dart]
format = '([$symbol($version )]($style))'
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[deno]
format = '([$symbol($version )]($style))'

[dotnet]
format = '([$symbol($version )(🎯 $tfm )]($style))'

[elixir]
format = '([$symbol($version \(OTP $otp_version\) )]($style))'
symbol = " "

[elm]
format = '([$symbol($version )]($style))'
symbol = " "

[erlang]
format = '([$symbol($version )]($style))'

[fennel]
format = '([$symbol($version )]($style))'
symbol = " "

[git_branch]
symbol = " "

[golang]
format = '([$symbol($version )]($style))'
symbol = " "

[guix_shell]
symbol = " "

[haskell]
format = '([$symbol($version )]($style))'
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[helm]
format = '([$symbol($version )]($style))'

[java]
format = '([$symbol($version )]($style))'
symbol = " "

[julia]
format = '([$symbol($version )]($style))'
symbol = " "

[kotlin]
format = '([$symbol($version )]($style))'
symbol = " "

[lua]
format = '([$symbol($version )]($style))'
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
format = '([$symbol($version )]($style))'
symbol = "󰆥 "

[ocaml]
format = '([$symbol($version )(\($switch_indicator$switch_name\) )]($style))'
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[opa]
format = '([$symbo($version ]($style))"'

[package]
format = '(is [$symbol$version]($style) )'
symbol = "󰏗 "

[perl]
format = '([$symbol($version )]($style))'
symbol = " " 

[php]
format = '([$symbol($version )]($style))'
symbol = " "

[purescript]
format = '([$symbol($version )]($style))'

[pijul_channel]
symbol = " "

[raku]
format = '([$symbol($version-$vm_version )]($style))'

[red]
format = '([$symbol($version )]($style))'

[rlang]
format = '([$symbol($version )]($style))'
symbol = "󰟔 "

[ruby]
format = '([$symbol($version )]($style))'
symbol = " "

[rust]
format = '([$symbol($version )]($style))'
symbol = " "

[scala]
format = '([$symbol($version )]($style))'
symbol = " "

[swift]
format = '([$symbol($version )]($style))'
symbol = " "


[vagrant]
format = '([$symbol($version )]($style))'

[vlang]
format = '([$symbol($version )]($style))'

[zig]
format = '([$symbol($version )]($style))'
symbol = " "