# https://ghostty.org/docs/config
# https://github.com/ghostty-org/ghostty/blob/main/src/config/Config.zig
window-decoration = true
gtk-tabs-location = bottom
# gtk-wide-tabs = false
# gtk-adwaita = true
# adw-toolbar-style = flat

resize-overlay = never

confirm-close-surface = false
window-save-state = never
window-padding-color = background
window-theme = ghostty
config-file = config

class = floating.ghostty

shell-integration-features = true

# Keybinds
# Floating mode focuses on splits and tabs.
# https://ghostty.org/docs/config/keybind
keybind = ctrl+shift+t=new_split:right
keybind = ctrl+shift+alt+t=new_split:down

# Previous/next split
# keybind = ctrl+shift+tab=goto_split:previous
#keybind = ctrl+tab=goto_split:next

keybind = ctrl+shift+left=goto_split:previous
keybind = ctrl+shift+right=goto_split:next
keybind = ctrl+left=goto_split:previous 
keybind = ctrl+right=goto_split:next
 
# Previous/next tab
keybind = ctrl+alt+left=previous_tab
keybind = ctrl+alt+right=next_tab
 
# Split resizing 
keybind = ctrl+shift+alt+enter=toggle_split_zoom
keybind = ctrl+shift+alt+e=equalize_splits
keybind = ctrl+shift+alt+up=resize_split:up,10
keybind = ctrl+shift+alt+down=resize_split:down,10
keybind = ctrl+shift+alt+left=resize_split:left,10
keybind = ctrl+shift+alt+right=resize_split:right,10
 
# Tab -> window, window -> tab
keybind = ctrl+t=new_tab
keybind = ctrl+shift+w=close_surface
keybind = alt+f4=close_surface