# https://ghostty.org/docs/config
# https://github.com/ghostty-org/ghostty/blob/main/src/config/Config.zig
window-decoration = true
gtk-tabs-location = bottom
# gtk-wide-tabs = false
# gtk-adwaita = true
# adw-toolbar-style = flat

resize-overlay = never

confirm-close-surface = false
window-save-state = never
window-padding-color = background
window-theme = ghostty
config-file = config

class = floating.ghostty

shell-integration-features = true

# Keybinds
# Tab -> window, window -> tab
keybind = ctrl+shift+w=close_surface 
keybind = ctrl+shift+e=new_split:right 
keybind = ctrl+shift+q=new_split:down