# Font rendering
# https://github.com/maximilionus/lucidglyph
set -gx FREETYPE_PROPERTIES "autofitter:no-stem-darkening=0 autofitter:darkening-parameters=500,0,1000,500,2500,500,4000,0 cff:no-stem-darkening=0 type1:no-stem-darkening=0 t1cid:no-stem-darkening=0"
set -gx QT_NO_SYNTHESIZED_BOLD 1
