# Proton
PROTON_USE_NTSYNC=1
PROTON_FSR4_UPGRADE=1
PROTON_DLSS_UPGRADE=1
DXVK_FRAME_RATE=144

# Increase Nvidia's shader cache size to 12GB
# https://wiki.cachyos.org/configuration/gaming/#increase-maximum-shader-cache-size
__GL_SHADER_DISK_CACHE_SIZE=12000000000