[tools]
bun = "latest"
go = "latest"
node = "latest"
rust = "nightly"
npm = "latest"
python = "3.14.2"
uv = "latest"
zig = "0.14.1"
zls = "0.14.0"
pnpm = "latest"
ruby = "4.0.3"
watchexec = "latest"

[settings]
experimental = true