[tools]
bun = "latest"
dprint = "latest"
go = "latest"
node = "latest"
rust = "nightly"
npm = "latest"
python = "system"
uv = "latest"
zig = "0.14.1"
zls = "0.14.0"
pnpm = "latest"


[settings]

status = {  
    show_env = true,
show_tools = true,
}
